package com.shipper.enums;

public enum FilterKeys {
	ID, PRODUCT_CODE, PRODUCT_CODE_IN, BATCH_NUMBER, BATCH_NUMBER_IN, MANUFACTURING_DATE, EXPIRY_DATE, WAREHOUSE_CODE, WAREHOUSE_CODE_IN, QUANTITY

}
